[package]
name = "l04"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
log4rs = "1.3.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.22"
serde_yaml = "0.9"
