[package]
name = "protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tonic-build.workspace = true
prost.workspace = true
tonic.workspace = true

[build-dependencies]
tonic-build.workspace = true