appenders:
  stdout:
    kind: console
  server:
    kind: rolling_file
    path: "{$path}/server.log"
    encoder:
      pattern: "{d(%y-%m-%d %H:%M:%S)} {h({l})} {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 500 mb
      roller:
        kind: fixed_window
        pattern: "{$path}/server-{}.log"
        base: 0
        count: 50      
  requests:
    kind: rolling_file
    path: "{$path}/requests.log"
    encoder:
      pattern: "{d(%y-%m-%d %H:%M:%S)} {h({l})} {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 500 mb
      roller:
        kind: fixed_window
        pattern: "{$path}/requests-{}.log"
        base: 0
        count: 50

root:
  level: info
  appenders:
    - stdout
    - server
  
# loggers:
